Czasy joinow
PiotrMaciejKowalski/BigData2022-actors pull request #13
Opened 2022-11-20 19:30 UTC by KarolinaWrobel

2022-11-22 20:10 UTC, PiotrMaciejKowalski requested changes

2022-11-22 20:10 UTC, PiotrMaciejKowalski commented on colabs/Czasy_joinow.ipynb
> +        "from timeit import default_timer as timer\n",
jest dużo prostsza metoda
```
%%time
```
na początku komórki

2022-11-22 20:10 UTC, PiotrMaciejKowalski commented on colabs/Czasy_joinow.ipynb
> +        "print(\"joined table size: \", (data1.count(), len(data1.columns)), \"time of joining tables: \", end-start)"
dopiero count jest akcją sparkową - zatem w chwili wykonania end = timer() join nie jest jeszcze wykonany.

może dlatego te czasy wyszły dziwne.

2022-11-22 20:11 UTC, PiotrMaciejKowalski commented
Gdyby nie to, że timery nie łapały faktycznego joina to bym puścił te timeit - bo to i tak notatnik one-timer. Ale tak - to poproszę o ponowne przeliczenie.

2022-11-23 07:44 UTC, KarolinaWrobel commented on colabs/Czasy_joinow.ipynb
> +        "from timeit import default_timer as timer\n",
zmienione

2022-11-23 07:44 UTC, KarolinaWrobel commented on colabs/Czasy_joinow.ipynb
> +        "print(\"joined table size: \", (data1.count(), len(data1.columns)), \"time of joining tables: \", end-start)"
zmienione

2022-11-23 18:50 UTC, PiotrMaciejKowalski approved these changes, later dismissed

2022-11-23 19:31 UTC, PiotrMaciejKowalski approved these changes

2022-11-23 19:31 UTC, merged