Zaczytanie nowych baz
PiotrMaciejKowalski/BigData2022-actors pull request #16
Opened 2022-11-22 20:34 UTC by emiliakotlarska

2022-11-22 20:42 UTC, PiotrMaciejKowalski requested changes

2022-11-22 20:42 UTC, PiotrMaciejKowalski commented on zaczytanie_nowych_danych
> +{
przenieść do właściwego katalogu

2022-11-23 20:37 UTC, emiliakotlarska commented on zaczytanie_nowych_danych
> +{
Zrobione

2022-11-23 21:45 UTC, PiotrMaciejKowalski requested changes

2022-11-23 21:45 UTC, PiotrMaciejKowalski commented on colabs/Wczytanie_nowych_danych.ipynb
> +{
w przypadku nagród emmy coś chyba poszło nie tak
```+----------------+--------+----+
|             _c0|     _c1| _c2|
+----------------+--------+----+
|            name|category|role|
|   Comedy Series|  Comedy|main|
|      Lead Actor|  Comedy|main|
|    Lead Actress|  Comedy|main|
|Supporting Actor|  Comedy|main|
+----------------+--------+----+
```

2022-11-23 21:45 UTC, PiotrMaciejKowalski commented on colabs/Wczytanie_nowych_danych.ipynb
> +  "nbformat_minor": 0,
po prawdzie w tym notatniku nie ma sensu importować danych imdb. Może zatem usunąć te nadmiarowe sekcje.

2022-11-23 21:45 UTC, PiotrMaciejKowalski commented on colabs/Wczytanie_nowych_danych.ipynb
> +    "colab": {
Przydałaby się informacja jak pobrane do offile zbiory danych można znaleźć (gdzie są współdzielone)

2022-12-08 01:07 UTC, emiliakotlarska commented on colabs/Wczytanie_nowych_danych.ipynb
> +{
poprawione

2022-12-08 11:32 UTC, emiliakotlarska commented
Poprawione

2022-12-11 07:27 UTC, PiotrMaciejKowalski approved these changes

2022-12-11 07:27 UTC, merged