Cu 30u4v4d analiza wizualizacja
PiotrMaciejKowalski/BigData2022-actors pull request #17
Opened 2022-11-26 18:12 UTC by Machcio

2022-11-26 18:12 UTC, PiotrMaciejKowalski commented
Task linked: [CU-30u4v4d Analiza, wizualizacja](https://app.clickup.com/t/30u4v4d)

2022-12-14 18:07 UTC, PiotrMaciejKowalski requested changes

2022-12-14 18:07 UTC, PiotrMaciejKowalski commented on colabs/Wizualizacje_analiza.ipynb
> +{
Jedna tylko uwaga. Na czele notatnika prosiłbym o zapisanie opisu notatnika - po co on powstał, co chcieliśmy zrobić etc oraz dopisać jakie uzyskano wnioski z obliczeń poniżej.

2022-12-20 11:43 UTC, Machcio commented on colabs/Wizualizacje_analiza.ipynb
> +{
W commicie jest już opis i wnioski i wybrane wizualizacje, badające kolumny "startYear/endYear/knownForTitles".

2022-12-22 15:59 UTC, PiotrMaciejKowalski approved these changes

2022-12-22 15:59 UTC, merged