Add files via upload
PiotrMaciejKowalski/BigData2022-actors pull request #2
Opened 2022-10-30 10:26 UTC by magdalenp

notatnik z setup sparka, pobiera dane, rozpakowuje i wczytuje

2022-10-30 10:27 UTC, magdalenp commented
notatnik z setup sparka, pobiera dane, rozpakowuje i wczytuje

2022-10-30 11:39 UTC, KirGear submitted a review, later dismissed
Chyba wszystko w porządku.
(Ja jeszcze się uczę używać GitHuba)

2022-10-30 20:27 UTC, PiotrMaciejKowalski commented
Proszę utworzyć sekcje i pod-sekcja do uporządkowania kodu
Najlepiej jedna sekcja nadrzędna 1. Setup sparka oraz wczytania danych
A potem osobne subsekcje dotyczące , setup sparka , pobrania danych i ich wczytania.

2022-10-30 20:33 UTC, PiotrMaciejKowalski requested changes

2022-10-30 20:33 UTC, PiotrMaciejKowalski commented on Wczytanie_danych.ipynb
> +{
Oczekiwałbym na początku jednej komórki ze wszystkimi importami z notatnika. pozwoli to monitorować zależności notatnika.

2022-10-30 20:33 UTC, PiotrMaciejKowalski commented on Wczytanie_danych.ipynb
> +        "!pip install pyspark py4j\n",
Nie mieszać komórek z kodem bashowym i pythonowym

2022-10-30 20:33 UTC, PiotrMaciejKowalski commented on Wczytanie_danych.ipynb
> +        "df_name_basics.show()\n",
Zmniejszyć liczbę showów do mniejszej. Najlepiej zapisanej w początkowej części notatnika jako stała np.
```
DEFAULT_SHOW_COUNT = 3
```

2022-10-30 20:33 UTC, PiotrMaciejKowalski commented on Wczytanie_danych.ipynb
> +{
notatnik nie jest we właściwej lokalizacji. powinien być w katalogu colabs.

2022-11-01 22:43 UTC, PiotrMaciejKowalski approved these changes

2022-11-01 22:44 UTC, merged