Doda now kolumn   ilo nagrd dla danego aktora
PiotrMaciejKowalski/BigData2022-actors pull request #22
Opened 2022-12-11 15:00 UTC by KarolinaWrobel

2022-12-13 14:13 UTC, PiotrMaciejKowalski requested changes
Trzeba do tego domergować refactoring

2022-12-13 17:37 UTC, KarolinaWrobel commented
Refactoring domerge'owany i zrobiłam też refactoring na dodaniu tych kolumn

2022-12-14 16:32 UTC, PiotrMaciejKowalski commented
czekam z review na merge Refactoringu.

2022-12-18 07:51 UTC, PiotrMaciejKowalski submitted a review, later dismissed

2022-12-18 07:52 UTC, PiotrMaciejKowalski approved these changes

2022-12-18 07:52 UTC, merged