Research metryk
PiotrMaciejKowalski/BigData2022-actors pull request #25
Opened 2022-12-15 01:54 UTC by Pawel180

2022-12-15 14:07 UTC, PiotrMaciejKowalski requested changes

2022-12-15 14:07 UTC, PiotrMaciejKowalski commented on Szkic_Metryki.md
> +poyzcja - pozycja aktora na liście. Mnożnik któego używamy z uwagi na wagę kolejności na liście(bardziej podobni są wcześniej)\
literówka

2022-12-15 14:07 UTC, PiotrMaciejKowalski commented on Szkic_Metryki.md
> +<pre>
daj 
"```python"

i 
"```" na końcu

2022-12-15 14:07 UTC, PiotrMaciejKowalski commented on Szkic_Metryki.md
> +Nasz model dla wybranego aktora szereguje aktorów ze zbioru i zwraca ustaloną liczbę najbardziej godnych polecenia. Kolejność wystąpienia aktorów na liście będzie od najbardziej podobnego do najmniej
literówka

2022-12-15 14:07 UTC, PiotrMaciejKowalski commented on Szkic_Metryki.md
> +Najbardziej przydatne będą parametry które pozwolą nam w czytelny sposób rozróżnić czy para aktorów jest do siebie podobna. Przykładem może być płeć gdzie dla dwóch wybraych aktorw jest ona jednakowa
literówka * 3

2022-12-16 21:42 UTC, Pawel180 commented on Szkic_Metryki.md
> +poyzcja - pozycja aktora na liście. Mnożnik któego używamy z uwagi na wagę kolejności na liście(bardziej podobni są wcześniej)\
Poprawione

2022-12-16 21:42 UTC, Pawel180 commented on Szkic_Metryki.md
> +<pre>
Zrobione

2022-12-16 21:43 UTC, Pawel180 commented on Szkic_Metryki.md
> +Nasz model dla wybranego aktora szereguje aktorów ze zbioru i zwraca ustaloną liczbę najbardziej godnych polecenia. Kolejność wystąpienia aktorów na liście będzie od najbardziej podobnego do najmniej
Poprawione

2022-12-16 21:46 UTC, Pawel180 commented on Szkic_Metryki.md
> +Najbardziej przydatne będą parametry które pozwolą nam w czytelny sposób rozróżnić czy para aktorów jest do siebie podobna. Przykładem może być płeć gdzie dla dwóch wybraych aktorw jest ona jednakowa
Poprawione, zamieniłem też alternatywę w przypadku płci na wykluczającą oraz dodałem krótki komentarz na temat ról granych przez aktorów.

2022-12-18 07:03 UTC, PiotrMaciejKowalski submitted a review, later dismissed

2022-12-18 07:03 UTC, PiotrMaciejKowalski commented on Szkic_Metryki.md
> +<pre>```python
Ale ten tag `pre` usuń

2022-12-18 18:53 UTC, Pawel180 commented on Szkic_Metryki.md
> +<pre>```python
Zrobione

2022-12-18 19:45 UTC, PiotrMaciejKowalski approved these changes

2022-12-18 19:55 UTC, merged