Inzynieria nowych cech   kodowanie
PiotrMaciejKowalski/BigData2022-actors pull request #45
Opened 2023-01-15 18:41 UTC by KarolinaWrobel

2023-01-16 22:49 UTC, PiotrMaciejKowalski requested changes

2023-01-16 22:49 UTC, PiotrMaciejKowalski commented on lib/adding_columns.py
> +    data = data.withColumn("types_code", array(types_list))
asercja na nie istnienie wcześniej nowo tworzonych kolumn

2023-01-16 22:49 UTC, PiotrMaciejKowalski commented on lib/adding_columns.py
> +    data = data.withColumn("genres_code", array(genres_list))
asercje na brak nowo tworzonych kolumn w `data`

2023-01-17 09:48 UTC, KarolinaWrobel commented on lib/adding_columns.py
> +    data = data.withColumn("types_code", array(types_list))
dodane

2023-01-17 09:48 UTC, KarolinaWrobel commented on lib/adding_columns.py
> +    data = data.withColumn("genres_code", array(genres_list))
dodane

2023-01-17 11:12 UTC, PiotrMaciejKowalski approved these changes

2023-01-17 12:29 UTC, merged